### ISSUE TITLE
Need project.jrubyexec {}

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#104]
For #102 I'm finding that I need to run `JRubyExec` multiple times in a single task, and right now I have no means to do that.

I think an analog to `project.javaexec {}` would be a useful addition

**Comment by ysb33r** [comment]
It already exists. Check the README - https://github.com/jruby-gradle/jruby-gradle-plugin/blob/master/README.md#jrubyexec-extension

**Comment by rtyler** [comment]
DERP! I was looking aronud in the code epecting to find something and I couldn't. Guess I'll read our documentation in the future :P
