### ISSUE TITLE
Combine .jrubydir generation with gem install

### ISSUE THREAD

**Issue by ysb33r** [jruby-gradle/jruby-gradle-plugin#109]
This is a follow-on from the conversation that started on the PR review - https://github.com/jruby-gradle/jruby-gradle-plugin/pull/108/files#r28513292.

The idea is to combine both tasks in to a single Ruby script which can then be run (with appropriate parameters passed from Gradle) as the new Gem Install.

I reckon that if someone can write the Rubt script, I can craft up somthing which will store it in plugin jar or generate it on the fly. 

(QUESTION: It is possible to tell jruby to execute a number of commands on the Jruby command-line? i.e. like for `groovy -e` or `perl -e`)

**Comment by mkristian** [comment]
yes you can build "longish" scripts with ```jruby -e``` no problem :)

**Comment by mkristian** [comment]
we need to check if we can drop the .jrubydir generation at this point. when packing a jar it happens anyways and for the jar it is needed. might even solve the issue with double entries inside the jar https://github.com/jruby-gradle/jruby-gradle-jar-plugin/issues/50

**Comment by ysb33r** [comment]
I think this is resolved by all of @mkristian's work. Can I close it?

**Comment by mkristian** [comment]
no this is not solved.

**Comment by rtyler** [comment]
This might be redundant once #159 is implemented

**Comment by rtyler** [comment]
This might also be redundant once #223 is implemented

**Comment by rtyler** [comment]
This is no longer needed since #225 will address generating `.jrubydir` files which are only needed in a packed jar scenario
