### ISSUE TITLE
GenerateGradleRb should define gradle.rb in the root project dir

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#112]
If you apply the plugin in a multiple subprojects, the first (or last I can't tell) one to define the `jrubyGenerateGradleRb` will have the `gradle.rb` file defined there.

Instead I think we should go to `"${rootProject.projectDir}/gradle.rb`

**Comment by ysb33r** [comment]
Yes and no. Each project it gets applied to should get one. It that does not happen it's a bug.

Secondly, the user should have control over where it get's applied. That would especially be true in a multi-project polyglot build.

If you want it in the root only then place the apply in the rootProject closure of the top build.gradle file.

<div>-------- Original message --------</div><div>From: "R. Tyler Croy" <notifications@github.com> </div><div>Date:01/05/2015  01:37  (GMT+00:00) </div><div>To: jruby-gradle/jruby-gradle-plugin <jruby-gradle-plugin@noreply.github.com> </div><div>Subject: [jruby-gradle-plugin] GenerateGradleRb should define gradle.rb in the
  root project dir (#112) </div><div>
</div>If you apply the plugin in a multiple subprojects, the first (or last I can't tell) one to define the jrubyGenerateGradleRb will have the gradle.rb file defined there.

Instead I think we should go to "${rootProject.projectDir}/gradle.rb
