### ISSUE TITLE
Setting jruby.defaultVersion must happen before loading of jar plugin

### ISSUE THREAD

**Issue by shiv123** [jruby-gradle/jruby-gradle-plugin#115]
With versions 0.1.16 of the base plugin and 0.1.3 of the jar plugin, I cannot overwrite the `defaultVersion` properly to `1.7.20` unless I do it before the loading of the jar plugin.

For example this:

```gradle
apply plugin: "com.github.jruby-gradle.base"
apply plugin: "com.github.jruby-gradle.jar"
jruby.defaultVersion = '1.7.20'
```

Will result in the `compile` and other configurations having `1.7.19` while others like `.jrubyJar` get `1.7.20`

If I change the ordering to:

```
apply plugin: "com.github.jruby-gradle.base"

jruby.defaultVersion = '1.7.20'

apply plugin: "com.github.jruby-gradle.jar"
```

Then everything does use the newer default version

**Comment by ysb33r** [comment]
Nice catch! Let's see what we can do.
