### ISSUE TITLE
Setting JRubyExec's configuration should follow Schalk's Gradle conventions

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#118]
I noticed this evening while working that the `configuration` property in the `JRubyExec` class lacks property style setters and getters, and instead acts simply as a class attribute.

```gradle
task spec(type: JRubyExec) {
  /* ... */
  configuration = 'rspec'
}
```

:-1: 

```gradle
task spec(type: JRubyExec) {
  /* ... */
  configuration configurations.rspec
}
```

:+1:

**Comment by ysb33r** [comment]
I'll have a PR for you by EOD :8ball:

**Comment by rtyler** [comment]
This has been addressed in some recent JRubyExec refactorings
