### ISSUE TITLE
I should be able to override jruby.defaultVersion or execVersion from the command line

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#131]
This would be great for testing newer version of JRuby with existing builds, e.g.

```
% ./gradlew check -Pjruby.execVersion=9.0.0.0.pre2
```

From what I've read this has to be manually accounted for in the plugin and doesn't come automatically

**Comment by mkristian** [comment]
+1

**Comment by ysb33r** [comment]
I don't think the plugin should provide that functionality. It is better that is provided in a bespoke manner in the build script, should the author prefer it as such.

**Comment by ysb33r** [comment]
Having said that, it would be better to do it via a system property, rather than the project property. There is some semantic invovled here. In this way if is effectivley a property of the plugin rather than the specific project.

**Comment by mkristian** [comment]
actually I was reading it as
```./gradlew check -Djruby.execVersion=9.0.0.0.pre2```

probably since I not aware what -P is meant for

**Comment by rtyler** [comment]
@ysb33r I'm fine with a system property, I can kind of understand why you don't think the functionality that the code should go into the plugin.

I think there is immense benefit to JRuby users and the JRuby core team by enabling this functionality across the board by default for jruby-gradle users. That would make it absolutely trivial for jruby-gradle projects to contribute feedback to the project on the success of jruby 9k which is pretty important IMO

**Comment by ysb33r** [comment]
> I think there is immense benefit to JRuby users and the JRuby core team by enabling this functionality across the board by default for jruby-gradle users. That would make it absolutely trivial for jruby-gradle projects to contribute feedback to the project on the success of jruby 9k which is pretty important IMO

I am with you on that. It will also allow to set up an additional travis axis to compile with the normal & 9K
versions.

I think you just need to do something like

```groovy
String defaultVersion = System.getProperty('jruby.defaultVersion') ?: '1.7.20'
String execVersion - System.getProperty('jruby.execVersion') ?: defaultVersion
```

**Comment by rtyler** [comment]
:+1: 

I'll submit a PR later today

**Comment by rtyler** [comment]
I'm back to thinking this should be a project property which affords the user the greatest amount of flexibility (IMHO) since they can take advantage of the `-P` CLI, `gradle.properties` and `~/.gradle/gradle.properties` delegation for setting it.

For projects at Lookout we're using `-PjrubyVersion=9.0.0.0` which allows the releng/build team to test projects with different JRuby versions easily, while allowing multi-project build authors to centralize their JRuby runtime version in the root project's `gradle.properties` file
