### ISSUE TITLE
Invoking `initScript` should imply `defaultMainClass()` by default

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#136]
I think using `initScript` should imply `defaultMainClass()`, there's no reason I should have to add both statements to my `jruby{}` configution block

**Comment by mkristian** [comment]
will be fixed with #138 in https://github.com/jruby-gradle/jruby-gradle-plugin/pull/138/files#diff-4950837d5586920dfe4f70640c7798e6R141 which does have a test

**Comment by mkristian** [comment]
is fixed with #138
