### ISSUE TITLE
consolidate the ```JRubyPrepareGems``` and ```JRubyPrepareJars```  into one task

### ISSUE THREAD

**Issue by mkristian** [jruby-gradle/jruby-gradle-plugin#141]
consolidate the ```JRubyPrepareGems``` and ```JRubyPrepareJars``` to be only one task ```JRubyPrepare``` setting up both gems and jars and the jars go into GEM_HOME/jars for consistency.

this is mostly rearranging things.

**Comment by rtyler** [comment]
Why? There's no downside to having the two tasks as far as I can tell

**Comment by mkristian** [comment]
once you at one method to install the jars in ```JRubyPrepareGems``` then you do not need ```JRubyPrepareJars``` anymore and do not need to think about the jar install diectory which you should configure in the same manner as the gem install dir - for the same reason you do change the first.

then ```JRubyPrepare``` is an empty task depending on ```JRubyPrepareGems``` only.

so instead of one extra method you get two more tasks and more config which is not obvious that this is tightly bound to the config for the gems.

* less code
* more user friendly

**Comment by rtyler** [comment]
*shrug* 

Okay :D

**Comment by ysb33r** [comment]
There quite a number of Gradle projects out there that use `jrubyPrepareGems` purely for obtaining GEMs. Some of those projects don't even care about packaging up GEMs unto a JAR again. 

Dropping this task will break a number of projects. It would be better to have a shell task that prints a warning and which then depends on a unified task.

**Comment by mkristian** [comment]
I was planning to keep ```jrubyPrepareGems``` by an empty task depending on ```jrubyPrepare`` and warning. @ysb33r would that do ?

**Comment by ysb33r** [comment]
To paraphrase, you want to create the equivalent:

```groovy
task jrubyPrepareGems << { log.lifecycle "jrubyPrepareGems is deprecated and will be removed in a future release. Use jrubyPrepare instead." }
jrubyPrepareGems.dependsOn 'jrubyPrepare'
```

```
@Deprecated
class JRubyPrepareGems extends JRubyPrepare {
  JRubyPrepareGems() {
    super()
    logger.lifecycle "JRubyPrepareGems is deprecated. Use JRubyPrepare instead"
 }
}
```

The latter might introduce a binary incompatibility, but I don;t think that is going to cause that much problems. I suspect most usages of `JRubyPrepareGems` are in scripts, not plugins (except for ours), It still might a versoin bump to `0.4` though.

**Comment by mkristian** [comment]
@ysb33r I thought that the ```JRubyPrepareGems``` can also declare some ```dependsOn 'jrubyPrepare'``` - if not then the ```class JRubyPrepareGems extends JRubyPrepare``` will do

**Comment by ysb33r** [comment]
> I thought that the JRubyPrepareGems can also declare some dependsOn 'jrubyPrepare' 

Preferably not, as you then force a dependency a script author does not want. IOW task classes should not add a dependency on a specific task instance.

**Comment by rtyler** [comment]
I believe this can be resolved now
