### ISSUE TITLE
Support proxy-less Gem resolution

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#180]
I've discussed this with @mkristian a bit, but basically what would be an ideal first pass implementation of supporting gem resolution "internally" in the Gradle process would be to embed the servlets code and then implement a function like:

```gradle
repositories {
   rubygems { url 'https://rubygems.org' }
}
```

Of course, the usage of the `rubygemsRelease()` function would do the same thing.

**Comment by mkristian** [comment]
fixed with #199
