### ISSUE TITLE
Document how to work effectively with "pre" versions of Gems

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#182]
#181 has made it clear that the supported behaviors both of [rubygems-servlets](http://github.com/torquebox/rubygems-servlets) and JRuby/Gradle when working with prerelease/alpha versions of gems is rather confusing.

This is something that I think should be thoroughly documented inside of the Base README

**Comment by mkristian** [comment]
in my opinion this should not be used unless you want all prereleased gems picked as well - where as picking a single prereleased gem should (does work with maven) via the release repo.

**Comment by rtyler** [comment]
This ticket isn't about using the `prereleases` maven repo so much as documenting how a JRuby/Gradle user should use a `pre`gem version

**Comment by mkristian** [comment]
sorry my comment was confusing without reading the comment from #181 

after fixing #181 prereleased gem dependencies should just pick a versions - version ranges will not work.
