### ISSUE TITLE
project.jruby.gemInstallDir and jarInstallDir need to be revisited/rethought

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#187]
With the push to get users to use separate Configurations for their gems, we should also consider revisiting how these work in `JRubyPluginExtension` as well.

One useful addition would be a method for getting the gemInstallDir for a specific configuration or setting it for a configuration.

**Comment by mkristian** [comment]
I am surprised that the jarInstallDir is still around and can be configured. it should be always gemInstallDir + "/jars"

and as far I can tell you can set it but is not used anywhere anymore

the Jars.lock file will be generated per configuration and resides in gemInstallDir + "/Jars.lock"

so I hope each configuration gets it own gemInstallDir per default.
