### ISSUE TITLE
'jruby-gradle-jar-plugin' integrations tests fail on Windows

### ISSUE THREAD

**Issue by abelsromero** [jruby-gradle/jruby-gradle-plugin#197]
I was trying to build the project on a Windows 8 local machine and I found that integration tests for jar-plugin fail due to a path constructions issue.

Just adding `.replaceAll("\\\\","/")` to lines [139 and 141](https://github.com/jruby-gradle/jruby-gradle-plugin/blob/master/jruby-gradle-jar-plugin/src/integTest/groovy/com/github/jrubygradle/jar/JRubyJarIntegrationSpec.groovy#L139-L141) fixed the issue.
This replacement should be transparent for unix systems.

**Comment by mkristian** [comment]
since I have a windows machine at hand. I rather replace ```absolutePath``` with ```absoluteFile.toURI().toURL()``` and let the java do the conversion. could you try this one out for me ? then we can pick a solution which works.

**Comment by abelsromero** [comment]
> I rather replace absolutePath with absoluteFile.toURI().toURL()

Much better indeed and works perfectly (on Ubuntu too). Since `file://`is no longer required for `url`, the final code would be:

```
    flatDir dirs: "${TESTREPO_LOCATION.absoluteFile.toURI().toURL()}"
    maven {
        url "${MAVENREPO_LOCATION.absoluteFile.toURI().toURL()}"
    }
```

**Comment by mkristian** [comment]
thanx a lot. will prepare a PR unless you are first :)

**Comment by abelsromero** [comment]
> thanx a lot. will prepare a PR unless you are first :)

master branch?

**Comment by rtyler** [comment]
@abelsromero yes, all PRs should be made against master. Thanks for finding the issue!

**Comment by abelsromero** [comment]
PR sent.

> Thanks for finding the issue!

It's no big deal. I have the custom to report everything, even little things.
Btw, if you want to test automatically against Windows, you can easily integrate AppVeyour. Works exactly like TravisCI but on Windows machines, here is an example https://github.com/asciidoctor/asciidoctorj/blob/master/appveyor.yml
