### ISSUE TITLE
Jar should not be packed with gems/cache/*.gem

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#200]
Right now the cache/ directory contents are being included in the packaged up jar file, but serve 100% no purpose other than to bloat the size of the package.

In one case internal to Lookout, the cache/ directory for a jar-based project is 14MB all on its own!

**Comment by rtyler** [comment]
One temporary work-around is to use:

```gradle
jrubyJar {
   exclude '**/*.gem'
}
```

**Comment by mkristian** [comment]
+1
