### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by ivanove** [jruby-gradle/jruby-gradle-plugin#206]
Hi all,

I try to use the simple example of print-script.rb but it gives me error when I "add import com.github.jrubygradle.JRubyExec"

when I delet it it gives me that error 
Error:(31, 0) Could not find property 'JRubyExec' on root project 'MyAPP'.

**Comment by rtyler** [comment]
@ivanove Make sure that the plugin is added to the top of the `build.gradle`, the example on the jruby-gradle.org homepage omits this for brevity but it mentions how this works in [this installing section](http://jruby-gradle.org/base/#installing).

Basically, the full thing is:

**build.gradle**
```gradle
buildscript {
    repositories { jcenter() }

    dependencies {
        classpath "com.github.jruby-gradle:jruby-gradle-plugin:1.0.3"
    }
}

apply plugin: 'com.github.jruby-gradle.base'

import com.github.jrubygradle.JRubyExec

dependencies {
    /* Using the built-in `jrubyExec` configuration to describe the
     * dependencies our JRubyExec-based tasks will need
     */
    jrubyExec "rubygems:colorize:0.7.7+"
}

task printSomePrettyOutputPlease(type: JRubyExec) {
    description "Execute our nice local print-script.rb"
    script "${projectDir}/print-script.rb"
}
```

The `buildscript` section is something provided by Gradle itself to allow the loading of plugins into the classpath of the build script when it executes.


Hope that helps!

**Comment by ivanove** [comment]
Yes, it works, thank you very much !
