### ISSUE TITLE
tags and published versions

### ISSUE THREAD

**Issue by dstine** [jruby-gradle/jruby-gradle-plugin#242]
Thank you for this project.

The latest tag I see in the repo is `v1.1.0`.

I see versions `1.1.1` and `1.1.2` published to JCenter, but not `1.1.0`. (https://bintray.com/jruby-gradle/plugins/jruby-gradle-plugin/view#release)

So I don't see any 1.1.x version that is both tagged in the repo and published to JCenter. I am new to this project, am I missing something?

**Comment by rtyler** [comment]
It looks like I forgot to push those versions, whoops! This has since been corrected.

The 1.1.2 version is the correct version to rely on since the 1.1.0 and 1.1.1 versions I had some mistakes in generating the POM files properly. 1.1.2 is proper and correct though :)

**Comment by dstine** [comment]
Yep, I see the `v1.1.2` tag now. Thanks.
