### ISSUE TITLE
rubygems() does not support repository URLs that require authentication.

### ISSUE THREAD

**Issue by raelik** [jruby-gradle/jruby-gradle-plugin#254]
I've found that if you try to use a repository URL in the form of http(s)://username:password@... for a rubygems repository that requires Basic auth, you will always get a `java.io.IOException: Server returned HTTP response code: 401 for URL: ...` exception, regardless if the username and password are correct or not.  I narrowed down the issue to a lack of support for this format of URL, or indeed basic auth support at all, in the nexus-ruby-tools library that https://github.com/torquebox/rubygems-servlets uses, specifically here: http://git.io/vCBp9

The following logic would need to be added before the line linked above, and before line 166 in the update() function in that same file, to make this work:

``` java
String userinfo = url.getURL().getUserInfo();
if(userinfo != null) {
  String basicAuth = "Basic " + DatatypeConverter.printBase64Binary(URLDecoder.decode(userinfo, 'UTF-8').getBytes(StandardCharsets.UTF_8));
  url.setRequestProperty ("Authorization", basicAuth);
}
```

There may be other places I haven't identified that would need similar additions.

In addition, import lines would need to be added for `javax.xml.bind.DatatypeConverter`, `java.net.URLDecoder`, and `java.nio.charset.StandardCharsets`. 

This issue should probably be submitted to Sonatype Nexus' OSS team, but it is unclear how to proceed with doing that. The git.io link above references code that they have since moved off of github.

**Comment by ysb33r** [comment]
In Gradle the convention is to use a crendentials block, which the underlying Maven/Ivy repository objects will pick up and use for authentication.

**Comment by raelik** [comment]
@ysb33r That being the case, the underlying nexus library would still need to be modified, albeit maybe in such a way to accept those credentials separately from the url.  Alternatively, the jruby-gradle plugin could prepend them to rubygems repository urls when appropriate.

**Comment by mkristian** [comment]
yes, the ```rubygems()`` configuration should have its own authentication part as ```maven()``` but that is another issue.

either the nexus-tools fix or we get a CachingProxyStorage.java with fix authentication into the rubygems-servlets. will check when sonatype plans to release a new nexus-oss for the old branch.

@raelik a more up to date repo is https://github.com/sonatype/nexus-public/tree/nexus-2.x/plugins/rubygem/nexus-ruby-tools

development happens internally but the public part gets mirrored there and the nexus-tools are public only.

**Comment by raelik** [comment]
@mkristian Thanks! I was digging in that repo but I couldn't find the ruby tools. Didn't think to look in the nexus-2.x branch.

**Comment by raelik** [comment]
So it looks like what I recommended would be ok as a quick hack to support basic auth using username:password in the URL, but a better long-term solution would be:

* Have CachingProxyServer accept credentials in its constructor
* Fix RubygemsServletContextListener in the rubygems-servlets lib to pull those credentials from init params (e.g. GEM_PROXY_USERNAME, GEM_PROXY_PASSWORD) and pass them along.
* Pass those credentials in jruby-gradle's RubygemsServlet when initializing the proxy server.

**Comment by mkristian** [comment]
this really depends on the the above rubygems-servlet issues solved first.

**Comment by raelik** [comment]
@mkristian :+1:

**Comment by rtyler** [comment]
I'm going to optimistically put this in the next release milestone *fingerscrossed*

**Comment by mkristian** [comment]
@raelik just wanted to patch the nexus library but I think we can easily overwrite the method here
https://github.com/sonatype/nexus-public/blob/nexus-2.x/plugins/rubygem/nexus-ruby-tools/src/main/java/org/sonatype/nexus/ruby/layout/CachingProxyStorage.java#L202

and add  the authentication bits to it. let's see if they just add it nexus as well.

**Comment by mkristian** [comment]
this would be the patch https://gist.github.com/mkristian/0ad2fc25ab806df83796 - I will test it tomorrow a see what nexus folk have to say.

**Comment by mkristian** [comment]
nope there is more to it :(

**Comment by mkristian** [comment]
anyways updated my gist https://gist.github.com/mkristian/0ad2fc25ab806df83796

**Comment by raelik** [comment]
@mkristian Looks good to me :+1:

**Comment by rtyler** [comment]
@mkristian has the latest releases of the nexus-tools libnraries included this patch making this ticket moot?
