### ISSUE TITLE
Version of jar-dependencies is not handled correctly

### ISSUE THREAD

**Issue by ysb33r** [jruby-gradle/jruby-gradle-plugin#270]
Currently there are a number of places where jar-dependencies version is set in both the base plugins and the jar plugin. The version here is still set at `0.1.15` as well.

The following files are culprits:
- `JRubyExec`
- `JRubyExecUtils`
- `JRubyJar`

We need to update the version and also  make the adjustment so that a user can also override the version form the configuration.

**Comment by rtyler** [comment]
This might be related to #274, would you mind confirming if I did the necessary work to fix this? I just noticed this after merging >_<

**Comment by rtyler** [comment]
This is "fixed" by #319 😄
