### ISSUE TITLE
jrubyPrepare fails with JRuby 9.1.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by robertpanzer** [jruby-gradle/jruby-gradle-plugin#277]
When building AsciidoctorJ with a current snapshot of JRuby 9.1.3.0 jrubyPrepare fails with this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
        at org.jruby.RubyInstanceConfig.<init>(RubyInstanceConfig.java:84)
        at org.jruby.Main.<init>(Main.java:101)
        at org.jruby.Main.main(Main.java:200)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
```
This didn't occur with any previous version.

Don't know where this problem is rooted, the jruby-gradle plugin or jruby, and if it will be a problem with the released version, nevertheless want to file it here.

**Comment by rtyler** [comment]
What version of Gradle is this with? Do you have a SHA1 of the commit in AsciidoctorJ to look at too?

**Comment by mkristian** [comment]
@robertpanzer did you build the snapshot yourself ? the org/objectweb/asm classes are repacked to org/jruby/org/objectweb/asm but the repacking should also update those references. something went wrong or is wrong with the build of jruby-complete I would say

**Comment by robertpanzer** [comment]
Sorry, reported in a hurry before leaving and still on a small screen.
I will collect all necessary information and add them here.

But I tried building the current asciidoctor-1.6.0 branch only upgrading
the JRuby dependency to a 9.1.3.0 snapshot from yesterday.
Iirc the version of the JRuby-gradle plugin is also already a bit old.

Am Mittwoch, 24. August 2016 schrieb Christian Meier :

**Comment by robertpanzer** [comment]
This is with Gradle 2.14 running Java 1.8.0_91.

Running `./gradlew clean build` shows the exception when running on this commit:
https://github.com/robertpanzer/asciidoctorj/commit/b6593b1cdcf443982c3a495f3795d16ce62bda08 
and after switching the jruby dependency to 9.1.3.0-SNAPSHOT.

I had a look at jruby-core-9.1.2.0.jar and the jruby-core-9.1.3.0-SNAPSHOT.jar and indeed 9.1.3.0 is missing these classes whereas 9.1.2.0 contains them. 

Will file this in the JRuby repo as well.

**Comment by robertpanzer** [comment]
Filed https://github.com/jruby/jruby/issues/4114

**Comment by robertpanzer** [comment]
Fixed in JRuby. (see jruby/jruby#4114)
