### ISSUE TITLE
Gradle 3 support

### ISSUE THREAD

**Issue by swistaczek** [jruby-gradle/jruby-gradle-plugin#287]
Gradle 3 was recently released as stable https://docs.gradle.org/current/release-notes :).

**Comment by rtyler** [comment]
GRADLE THREE WOOT

**Comment by fap-** [comment]
Any progress here?
The structure of gradles internal api has changed so the tasks are failing:
`Unable to load class com.github.jrubygradle.JRubyPrepare due to missing dependency org/gradle/api/internal/DynamicObject`

**Comment by ysb33r** [comment]
This will be fixe din the 1.6.0 release.

**Comment by rtyler** [comment]
Going to mark this as closed since we have the code merged already
