### ISSUE TITLE
lasagna.io is down

### ISSUE THREAD

**Issue by joankaradimov** [jruby-gradle/jruby-gradle-plugin#297]
It's been down for a couple of days now. And with it all gem dependencies fail.

I resolved it by adding this to my build.gradle:
```
repositories {
	mavenLocal()
	maven { url 'http://rubygems-proxy.torquebox.org/releases' }
}
```

But when lasagna.io is back (assuming it will be back), why not put both `http://rubygems.lasagna.io/proxy/maven/releases` and `http://rubygems-proxy.torquebox.org/releases` in the repositories so that there is a fallback.

**Comment by mkristian** [comment]
@rtyler any inside about the lasagna.io ? what you think about he the second repo ?

@ysb33r what implication does a second repo will have - first one wins or are both used all the time ?

**Comment by joankaradimov** [comment]
> what implication does a second repo will have - first one wins or are both used all the time ?

There's a short description of the behavior [here](https://docs.gradle.org/current/userguide/artifact_dependencies_tutorial.html#sec:repositories_tutorial)

It's near the end of the section:

> Gradle will look for a dependency in each repository in the order they are specified, stopping at the first repository that contains the requested module.

**Comment by ysb33r** [comment]
@mkristian As @joankaradimov has said.

**Comment by rtyler** [comment]
Looks like Namecheap didn't save some CNAME records correctly when I updated them last week. That has now been resolved and we're waiting for DNS to propagate.

**Comment by hiroyuki-sato** [comment]
Hello, @rtyler  @joankaradimov 

Does `rubygems.lasagna.io` still down?

```
telnet 52.167.117.165 80
Trying 52.167.117.165...
telnet: connect to address 52.167.117.165: Connection refused
telnet: Unable to connect to remote host
```



```
dig rubygems.lasagna.io in any

; <<>> DiG 9.8.3-P1 <<>> rubygems.lasagna.io in any
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64060
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 2

;; QUESTION SECTION:
;rubygems.lasagna.io.		IN	ANY

;; ANSWER SECTION:
rubygems.lasagna.io.	1708	IN	A	52.167.117.165

;; AUTHORITY SECTION:
lasagna.io.		33067	IN	NS	dns1.registrar-servers.com.
lasagna.io.		33067	IN	NS	dns2.registrar-servers.com.

;; ADDITIONAL SECTION:
dns1.registrar-servers.com. 129	IN	A	216.87.155.33
dns2.registrar-servers.com. 171152 IN	A	216.87.152.33

;; Query time: 4 msec
;; SERVER: 192.168.10.20#53(192.168.10.20)
;; WHEN: Thu Aug 31 09:23:14 2017
;; MSG SIZE  rcvd: 144
```

**Comment by rtyler** [comment]
@hiroyuki-sato sorry about the service issues, the rubygems-servlets proxy I operate keeps leaking memory which is quite frustrating!

Newer releases of jruby-gradle rely on both the torquebox and lasagna.io proxies FWIW

**Comment by hiroyuki-sato** [comment]
@rtyler Thank you for the reply. 
Today I succeed to access rubygems.lasagna.io.
Thank you again.
