### ISSUE TITLE
jrubyExec rubygems not installing all sub-dependencies

### ISSUE THREAD

**Issue by dillongilmore** [jruby-gradle/jruby-gradle-plugin#304]
I feel like what I'm doing here has to be extremely basic and I'm just missing something simple. The tl;dr of what I'm doing is the Ruby toolchain is difficult to work with so I want to generate a state site with Jekyll using Gradle instead of the standard MRI way. Here is my `build.gradle`.

    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath "com.github.jruby-gradle:jruby-gradle-plugin:+"
        }
    }
    
    apply plugin: 'com.github.jruby-gradle.base' 
    import com.github.jrubygradle.JRubyExec
    
    repositories {
        jcenter()
    }
    
    dependencies {
        jrubyExec 'rubygems:jekyll:3.5.2'
        jrubyExec 'rubygems:bundler:1.15.4'
        jrubyExec 'rubygems:minima:2.1.1'
    }
    
    def jekyllSite = System.getProperty('user.dir') + '/site'
    
    task jekyllNew(type: JRubyExec) {
        script 'jekyll'
        workingDir jekyllSite
        scriptArgs 'new', jekyllSite
    }

The next thing I do is run `gradle jekyllNew` and I get this error:

    Bundler::GemNotFound: Could not find gem 'tzinfo-data java' in any of the gem sources listed in your Gemfile.

Actually, that wasn't the first error I got, but it's the same thing with `jekyll-feed` instead. I went ahead and added jekyll-feed as an entry with the other `rubygems` entries and it was successfully installed but the build fails on the next dependency which in this case is tzinfo-data.

I have `bundler` and  `minima` in the build.gradle because Jekyll doesn't actually specify those dependencies whereas `jekyll-feed` and `tzinfo-data` are specified in the Gemfile, but aren't being downloaded. Here is a list of what's in my build's gems directory

    $ ls build/tmp/jrubyExec/gems/ | tr ' ' '\n'
    addressable-2.5.2
    bundler-1.15.4
    colorator-1.1.0
    ffi-1.9.18-java
    forwardable-extended-2.6.0
    jekyll-3.5.2
    jekyll-feed-0.9.2
    jekyll-sass-converter-1.5.0
    jekyll-watch-1.5.0
    kramdown-1.14.0
    liquid-4.0.0
    listen-3.0.8
    mercenary-0.3.6
    minima-2.1.1
    pathutil-0.14.0
    public_suffix-3.0.0
    rb-fsevent-0.10.2
    rb-inotify-0.9.10
    rouge-1.11.1
    safe_yaml-1.0.4
    sass-3.5.1
    sass-listen-4.0.0

Finally, my gradle version

    $ gradle --version
    ------------------------------------------------------------
    Gradle 3.2.1
    ------------------------------------------------------------
    Build time:   2012-12-21 00:00:00 UTC
    Revision:     none
    Groovy:       2.4.8
    Ant:          Apache Ant(TM) version 1.9.9 compiled on June 29 2017
    JVM:          1.8.0_141 (Oracle Corporation 25.141-b15)
    OS:           Linux 4.11.0-1-amd64 amd64

Any pointers would be great. Thanks!!

**Comment by mkristian** [comment]
putting the jekyll dependencies in Gemfile
```
source 'https://rubygems.org/'
gem 'jekyll', '3.5.2'
```
then I get
```
 bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies....
Installing public_suffix 3.0.0
Installing colorator 1.1.0
Installing ffi 1.9.18 (java)
Installing forwardable-extended 2.6.0
Installing rb-fsevent 0.10.2
Installing kramdown 1.14.0
Installing liquid 4.0.0
Installing mercenary 0.3.6
Installing rouge 1.11.1
Installing safe_yaml 1.0.4
Using bundler 1.14.3
Installing addressable 2.5.2
Installing rb-inotify 0.9.10
Installing pathutil 0.14.0
Installing sass-listen 4.0.0
Installing listen 3.0.8
Installing sass 3.5.1
Installing jekyll-watch 1.5.0
Installing jekyll-sass-converter 1.5.0
Installing jekyll 3.5.2
Bundle complete! 1 Gemfile dependency, 20 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

which is exactly what jruby-gradle is downloading comparing it to your list.

anything in any Gemfiles is not part of the transitive dependencies of any gem and will not be downloaded by gradle or maven or bundler. so any missing gems you need to add manually to your list of dependencies.

hope I did not miss something here.

**Comment by rtyler** [comment]
I am not able to reproduce any issues here with the latest relaese
