### ISSUE TITLE
`Content is not allowed in prolog` while installing a gem from local Maven repo (jruby-gradle.base)

### ISSUE THREAD

**Issue by abelsromero** [jruby-gradle/jruby-gradle-plugin#305]
Hi,

Installation of a gem from a local maven repo fails with the message `Content is not allowed in prolog` in the new `Trusty` images of TravisCI.
I have tested many things an I am out of ideas, any help will be appreciated.

At the end of Asciidoctorj build script for Travis we test the code against the upstream Asciidoctor gem from master branch. This is done with this script https://github.com/asciidoctor/asciidoctorj/blob/master/test-asciidoctor-upstream.sh.
It basically:
. Downloads Asciidoctor master code.
. Installs it locally using `gem-maven-plugin` and a template pom.xml.
. Then runs Asciidoctorj build pointing the gem version to the local one (see the `PasciidoctorGemVersion=$ASCIIDOCTOR_VERSION`).

I know this message 99% of times comes from encoding issues, but even changing encoding of the local pom in my machine did not reproduce the issue. I tried on Windows 8.1 and an Ubuntu VM and in all cases this works fine 😞 So I am pretty lost...

*plugin*: jruby-gradle.base
*version*: 1.4.0 and 1.5.0
*environment*: new TravisCI `Trusty` images (openjdk8, oraclejdk8 and openjdk7)

/cc @robertpanzer

**Comment by abelsromero** [comment]
![error_jruby](https://user-images.githubusercontent.com/5781153/30251975-b9ec86b6-966a-11e7-90fe-34943cfefa59.PNG)

**Comment by rtyler** [comment]
@abelsromero since this ticket is pretty old, and trusty is now super old too, I am going to close this ticket out.

I haven't personally seen it anywhere else since
