### ISSUE TITLE
http://rubygems.lasagna.io is currently not available

### ISSUE THREAD

**Issue by markus-meisterernst** [jruby-gradle/jruby-gradle-plugin#306]
Hi, 

I tried to build HTML Pages with Asciidoctor in my gradle build.
It accessess http://rubygems.lasagna.io, which is currently not available.

relevant build.gradle excerpts:

plugins {
    id 'org.asciidoctor.convert' version '1.5.3'
    // we need this plugin to add ruby gems
    id 'com.github.jruby-gradle.base' version '1.3.0'
 }

...
allprojects {
    apply plugin: 'java'
    apply plugin: 'groovy'
    apply plugin: 'org.asciidoctor.convert'
    apply plugin: 'com.github.jruby-gradle.base'
   ...
}

dependencies {
...
    compile 'org.asciidoctor:asciidoctorj:1.5.5'
    compile ('org.asciidoctor:asciidoctorj-groovy-dsl:1.0.0.preview2') {
        exclude group: 'org.codehaus.groovy', module: 'groovy-all'
        exclude group: 'org.asciidoctor', module: 'asciidoctorj'
    }
   
...
    // this is the gem we need for diagrams
    gems 'rubygems:asciidoctor-diagram:1.4.0'
    gems 'rubygems:asciidoctor:1.5.5'
}

Could you, please, have a look at why the site http://rubygems.lasagna.io is down. 
Or is it possible to use a different Proxy than http://rubygems.lasagna.io ? How would I configure it ? 

Thanks for any help.

Cheers,

Markus

:jrubyPrepare FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jrubyPrepare'.
> Could not resolve all dependencies for configuration ':gems'.
   > Could not resolve rubygems:asciidoctor-diagram:[1.4.0,1.4.0].
     Required by:
         project :
      > Could not resolve rubygems:asciidoctor-diagram:[1.4.0,1.4.0].
         > Failed to list versions for rubygems:asciidoctor-diagram.
            > Unable to load Maven meta-data from http://rubygems.lasagna.io/proxy/maven/releases/rubygems/asciidoctor-diagram/maven-metadata.xml.
               > Could not GET 'http://rubygems.lasagna.io/proxy/maven/releases/rubygems/asciidoctor-diagram/maven-metadata.xml'. Received status code 503 from server: Service Unavailable
   > Could not resolve rubygems:asciidoctor:[1.5.5,1.5.5].
     Required by:
         project :
      > Could not resolve rubygems:asciidoctor:[1.5.5,1.5.5].
         > Failed to list versions for rubygems:asciidoctor.
            > Unable to load Maven meta-data from http://rubygems.lasagna.io/proxy/maven/releases/rubygems/asciidoctor/maven-metadata.xml.
               > Could not GET 'http://rubygems.lasagna.io/proxy/maven/releases/rubygems/asciidoctor/maven-metadata.xml'. Received status code 503 from server: Service Unavailable

**Comment by ysb33r** [comment]
Upgrade to latest version version of tbe base plugin. It has a fallback for Torquebox.


Sent from my Samsung device

-------- Original message --------

**Comment by markus-meisterernst** [comment]
Thank you very much, upgrading to version 1.5.0 resolved the issue.
