### ISSUE TITLE
gradleTest fails : rubygems.lasagna.io refused

### ISSUE THREAD

**Issue by amiracam** [jruby-gradle/jruby-gradle-plugin#308]
5:28:15 AM: Executing task 'gradleTest'...

:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
Download https://jcenter.bintray.com/org/jruby/jruby-complete/1.7.19/jruby-complete-1.7.19.pom
Download https://jcenter.bintray.com/org/jruby/jruby-complete/1.7.19/jruby-complete-1.7.19.jar
:jruby-gradle-base-plugin:gradleDistributionDownloader
:jruby-gradle-base-plugin:compileJava UP-TO-DATE
:jruby-gradle-base-plugin:compileGroovy
:jruby-gradle-base-plugin:processResources
:jruby-gradle-base-plugin:classes
:jruby-gradle-base-plugin:jar
:jruby-gradle-base-plugin:gradleTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jruby-gradle-base-plugin:gradleTest'.
> Could not resolve all dependencies for configuration ':jruby-gradle-base-plugin:gradleTest'.
   > Could not resolve rubygems:credit_card_validator:1.1.0.
     Required by:
         com.github.jruby-gradle:jruby-gradle-base-plugin:1.5.1
      > Could not resolve rubygems:credit_card_validator:1.1.0.
         > Could not get resource 'http://rubygems.lasagna.io/proxy/maven/releases/rubygems/credit_card_validator/1.1.0/credit_card_validator-1.1.0.pom'.
            > Could not GET 'http://rubygems.lasagna.io/proxy/maven/releases/rubygems/credit_card_validator/1.1.0/credit_card_validator-1.1.0.pom'.
               > Connection to http://rubygems.lasagna.io refused

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.582 secs
Connection refused (Connection refused)
5:28:41 AM: Task execution finished 'gradleTest'.

**Comment by ysb33r** [comment]
Mmm... we still have the lasagne.io issue. I'll have a quick look at the test code.

**Comment by amiracam** [comment]
I ran your example and as is i.e. pointing to 1.5.0 works, my main problem is that the jruby gradle plugin does not play nice with IDEA or vice versa something I brought up at least on the Gitter channel sometime ago, this morning I'm going to try a strategy where I turn off IDEA gradle integration , will have to use bundler for gem loading since that's required for IDEA's intellisense and debugging, use Gradle for jar loading via Jruby gradle or vanilla gradle, and finally use Jruby gradle to generate the fat jar :) , I believe that Jruby gradle will do the right job in packaging a non rack micro service app in this case based of Ratpack,  I also prefer Gradle for jar dependency management and this app has a bigger mix of Java packages

**Comment by rtyler** [comment]
Looks like on the server side there was a new and exciting failure mode. The docker daemon which runs that proxy decided to stop servicing *all* requests, while still _appearing_ to run normally.

**Comment by rtyler** [comment]
rubygems.lasagna.io is back up again. :man_facepalming:

**Comment by amiracam** [comment]
I got another lasagna error which is making me hungry :) , too close to lunch, this time I added the gem sequel but without any version id and got the error stack below. I think I have asked this before but isn't there a way of asking jrubyJars to look to another gemset / jar location  , local preferred since I may have had the gems and jars retrieved by the time I actually need the shadow fat jar 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':prepareJRubyJar'.
> Could not resolve all files for configuration ':jrubyJar'.
   > Could not resolve rubygems:sequel:[,].
     Required by:
         project :
      > Could not resolve rubygems:sequel:[,].
         > Could not get resource 'http://rubygems-proxy.torquebox.org/releases/rubygems/sequel/%5B,%5D/sequel-%5B,%5D.pom'.
            > Could not GET 'http://rubygems-proxy.torquebox.org/releases/rubygems/sequel/%5B,%5D/sequel-%5B,%5D.pom'. Received status code 500 from server: Internal Server Error
      > Could not resolve rubygems:sequel:[,].
         > Could not get resource 'http://rubygems.lasagna.io/proxy/maven/releases/rubygems/sequel/%5B,%5D/sequel-%5B,%5D.pom'.
            > Could not GET 'http://rubygems.lasagna.io/proxy/maven/releases/rubygems/sequel/%5B,%5D/sequel-%5B,%5D.pom'.
               > Connect to rubygems.lasagna.io:80 [rubygems.lasagna.io/52.167.117.165] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed
charles-macbook:JrubyGradleTest5 charles$

**Comment by amiracam** [comment]
just tried it again , did not get the connection refused error but still no cigar, perhaps I have to fully specify the sequel version id ?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':prepareJRubyJar'.
> Could not resolve all files for configuration ':jrubyJar'.
   > Could not resolve rubygems:sequel:[,].
     Required by:
         project :
      > Could not resolve rubygems:sequel:[,].
         > Could not get resource 'http://rubygems-proxy.torquebox.org/releases/rubygems/sequel/%5B,%5D/sequel-%5B,%5D.pom'.
            > Could not GET 'http://rubygems-proxy.torquebox.org/releases/rubygems/sequel/%5B,%5D/sequel-%5B,%5D.pom'. Received status code 500 from server: Internal Server Error
      > Could not resolve rubygems:sequel:[,].
         > Could not get resource 'http://rubygems.lasagna.io/proxy/maven/releases/rubygems/sequel/%5B,%5D/sequel-%5B,%5D.pom'.
            > Could not GET 'http://rubygems.lasagna.io/proxy/maven/releases/rubygems/sequel/%5B,%5D/sequel-%5B,%5D.pom'. Received status code 500 from server: Server Error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

**Comment by amiracam** [comment]
yep, that was it , need a version id
