### ISSUE TITLE
Fails to resolve dependencies using Gradle 4.3

### ISSUE THREAD

**Issue by facewindu** [jruby-gradle/jruby-gradle-plugin#316]
Using Gradle 4.3, we cannot resolve rubygems with jruby-gradle-plugin 1.5.0

```
Execution failed for task ':jrubyPrepare'.
> Could not resolve all files for configuration ':gems'.
   > Could not resolve rubygems:slim:[3.0.8,3.0.8].
     Required by:
         project :
      > Skipped due to earlier error 
```

See attached reproduction project
[jruby-test.zip](https://github.com/jruby-gradle/jruby-gradle-plugin/files/1437130/jruby-test.zip)

Execute `./gradlew jrubyPrepare` to see the above error.
Switching the wrapper back to 4.2.1 works: `./gradlew wrapper --gradle-version 4.2.1; ./gradlew jrubyPrepare`

**Comment by boris-petrov** [comment]
@rtyler, @ysb33r - this is kind of urgent - we cannot update to Gradle 4.3 because of that. Do you have any ideas what might the problem be?

**Comment by ysb33r** [comment]
I'll look at it later this week when I have spare time.

**Comment by rtyler** [comment]
I understand the frustration, but please keep in mind that nobody around here is paid to work on JRuby/Gradle. :smile:

**Comment by boris-petrov** [comment]
Absolutely, I didn't mean any offence. :) Sorry if I sounded harsh. Just wanted to get your attention on this. Hopefully you can resolve it. :) Thanks for the hard work on this plugin, it's irreplaceable for us. :)

**Comment by ysb33r** [comment]
@boris-petrov Any chance you can run Gradle with `--debug` and dump the log for me?

**Comment by ysb33r** [comment]
@boris-petrov @facewindu Try this as a workaround for the time being

```groovy
jruby {
    defaultRepositories = false
}

repositories {
    jcenter()
    maven { url com.github.jrubygradle.JRubyPlugin.TORQUEBOX_RUBYGEMS_RELEASE_URL }
}
```

I believe the issue is caused by the breaking change introduced in Gradle 4.3: https://docs.gradle.org/current/release-notes.html#avoid-checking-other-repositories-when-dependency-resolution-in-one-repository-fails

**Comment by ysb33r** [comment]
I just tried a SNAPSHOT version of Gradle 4.3.1 and I can confirm that it solves the problem. I am not going to fix this for now. I suggest you stick with 4.2.1 and wait until 4.3.1 is released.

**Comment by boris-petrov** [comment]
@ysb33r - thanks a bunch for the research! We'll be waiting for a fix from Gradle then. You don't need the `--debug` log any more, I guess?

**Comment by ysb33r** [comment]
> You don't need the --debug log any more, I guess?

@boris-petrov No, not needed. 

As a side-note  managed to reproduce the problem within the base plugin's build by just adding  

```groovy
gradleTest.gradleArguments `--debug`
```

**Comment by facewindu** [comment]
Gradle 4.3.1 has just been released.
