### ISSUE TITLE
Remove support for JRuby 1.7.x

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#319]
Per discussion with @mkristian in Gitter. 1.7 is end of lifed and our limited bandwidth for JRuby/Gradle makes it no longer worth supporting.

- [x] Ensure removal coincides with a major version change for the plugin suite.
- [x] Update README to mention.
- [ ] Update docs to mention it as well.
- [ ] Check that minimum JDK version matches at least the minimum that is required for JRuby 9k,

**Comment by ysb33r** [comment]
I updated your descirption and added 4 TODOs.

**Comment by rtyler** [comment]
>  Ensure removal coincides with a major version change for the plugin suite.

@ysb33r do you think I should just call 1.6.0 a "2.0" across the board instead?

**Comment by ysb33r** [comment]
Let's go for 1.6.0 as we are not actually making major changes to the DSL itself.

**Comment by ysb33r** [comment]
I think we should consider going to 2.0 now as we are going to eventually make a bunch of DSL changes.
