### ISSUE TITLE
Cannot install RuboCop 0.58.{1,2}

### ISSUE THREAD

**Issue by boris-petrov** [jruby-gradle/jruby-gradle-plugin#328]
In [this](https://github.com/rubocop-hq/rubocop/commit/e41a2d5bd5b33cba1219e0f798397fac9b8fe543) commit, RuboCop added a filter on the `parser` dependency version. Then they released 0.58.1. Now they've released 0.58.2 and I cannot update to either version. The error that I'm getting is:

```
> Could not resolve rubygems:parser:(=2.5.1.1,).
  Required by:
      project :features > rubygems:rubocop:0.58.2
   > there is no overlap for (=2.5.1.1,99999) and (=2.5.1.1,)
```

Original issue was in [JRuby](https://github.com/jruby/jruby/issues/5260). They told me to post here. @mkristian can help more I think.

**Comment by mkristian** [comment]
@boris-petrov right this line is https://github.com/rubocop-hq/rubocop/commit/e41a2d5bd5b33cba1219e0f798397fac9b8fe543#diff-458bc38d82061cdac508dfb1be2b918bR39 is indeed the problem.

**Comment by boris-petrov** [comment]
@mkristian - do you mean that this is some unsupported "syntax" that RuboCop is using or this is a bug in the parsing of version ranges by JRuby Gradle?

**Comment by mkristian** [comment]
no actually it is a bug in https://github.com/torquebox/maven-tools which is used by the gem-proxy server which 'translates' the rubygems.org into a maven repository.

@boris-petrov so you could try and add something like `gems 'rubygems:parser:2.5.1.2+'`

as the fix will take its time to reach the proxy-server code we need to deal with this 'broken version' on jruby gradle as well by just deleting any '=' from the versions range completely just after (I guess): https://github.com/jruby-gradle/jruby-gradle-plugin/blob/master/jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/internal/GemVersion.groovy#L69

be my friend to try this, as I will not find before Sunday to do some coding.

**Comment by boris-petrov** [comment]
@mkristian - adding `rubygems:parser:2.5.1.2+` as an explicit dependency worked and RuboCop 0.58.2 is installed and works correctly. Thanks for that!

I'll leave you to decide whether to close the issue and open a new one somewhere else or leave it here. If you do the former, please link it to this one so I can subscribe to it to follow the progress.

Thanks again!
