### ISSUE TITLE
Unable to load Maven meta-data from http://rubygems.lasagna.io/proxy/maven/releases/rubygems/rspec/maven-metadata.xml

### ISSUE THREAD

**Issue by piersf** [jruby-gradle/jruby-gradle-plugin#329]
Hello there,

My apologies if this is not the right place for this issue. 
Our gradle project tries to download rubygems from http://rubygems.lasagna.io/proxy/maven/releases/rubygems/rspec/maven-metadata.xml

The piece of code in the `build.gradle` file is:

```
repositories {
    mavenCentral()
}

apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin
apply plugin: com.github.jrubygradle.JRubyPlugin

dependencies {
    jrubyExec 'rubygems:rspec:3.3.0'
    jrubyExec 'rubygems:dockerspec:0.3.+'
}
```

But since last week, this is now failing with the below errors:

```
> Could not resolve all dependencies for configuration ':DOCKER.Base.Centos:jrubyExec'.
   > Could not resolve rubygems:rspec:[3.6.0,3.6.0].
     Required by:
         DOCKER.Base.Centos:unspecified
      > Could not resolve rubygems:rspec:[3.6.0,3.6.0].
         > Failed to list versions for rubygems:rspec.
            > Unable to load Maven meta-data from http://rubygems.lasagna.io/proxy/maven/releases/rubygems/rspec/maven-metadata.xml.
               > Could not GET 'http://rubygems.lasagna.io/proxy/maven/releases/rubygems/rspec/maven-metadata.xml'.
                  > The target server failed to respond
   > Could not resolve rubygems:dockerspec:[0.3,0.3.99999].
     Required by:
         DOCKER.Base.Centos:unspecified
      > Could not resolve rubygems:dockerspec:[0.3,0.3.99999].
         > Failed to list versions for rubygems:dockerspec.
            > Unable to load Maven meta-data from http://rubygems.lasagna.io/proxy/maven/releases/rubygems/dockerspec/maven-metadata.xml.
               > Could not GET 'http://rubygems.lasagna.io/proxy/maven/releases/rubygems/dockerspec/maven-metadata.xml'.
                  > The target server failed to respond
```

It seems that [http://rubygems.lasagna.io/proxy/maven/releases/rubygems/dockerspec/maven-metadata.xml](http://rubygems.lasagna.io/proxy/maven/releases/rubygems/dockerspec/maven-metadata.xml) is now down. And it appears to have been down for the past 6-7 days. There's another issue found here https://github.com/asciidoctor/asciidoctor-gradle-examples/issues/38, that reports rubygems.lasagna.io to have been down since 6 days ago.

Anyone knows if this site is going to come back up? And if not, how can i change my `build.gradle` file, to download these gems from elsewhere?

Thank you,

**Comment by mkristian** [comment]
@rtyler could you look into this ?

**Comment by rtyler** [comment]
Ahck, right, I let that domain lapse. I forgot that anything was actually running there. Whoops!

It's a bit slower, but you may be able to use [the built-in Gem proxy](http://jruby-gradle.org/base/#using-the-built-in-gem-proxy) which @mkristian added a couple years ago.

**Comment by piersf** [comment]
Hi @mkristian, @rtyler ,

Thank you for your replies!

Looking at the link you pasted, i did some changes to the `build.gradle` file, but it does not seem to work and I'm doing something wrong. Now the file looks like:

```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        //classpath 'com.bmuschko:gradle-docker-plugin:2.6.7'
        classpath 'com.bmuschko:gradle-docker-plugin:3.2.5'
        //classpath 'com.github.jruby-gradle:jruby-gradle-plugin:1.4.0'
        classpath "com.github.jruby-gradle:jruby-gradle-plugin:[1.4.0,2.0)"
    }
}

apply plugin: 'com.github.jruby-gradle.base'

/* Disable our default repositories */
jruby.defaultRepositories false

repositories {
    mavenCentral()
    rubygems('https://rubygems.org')
}

apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin
apply plugin: com.github.jrubygradle.JRubyPlugin

dependencies {
    jrubyExec 'rubygems:rspec:3.3.0'
    jrubyExec 'rubygems:dockerspec:0.3.+'
}

import org.apache.tools.ant.filters.ReplaceTokens
import com.bmuschko.gradle.docker.tasks.image.*
import com.github.jrubygradle.JRubyExec
```

When i then execute the build, it fails with the below error:

```
A problem occurred evaluating project ':DOCKER.Testing.CI-TestRig'.
> Could not open dsl class cache for script '/path/to/project/DockerImageBuild/gradle/docker/imageTasks.gradle' (/home/git/username/.gradle/caches/2.8/scripts/imageTasks_15chbt6wct5zg0kf9m3tznlcc/dsl).
   > com/github/jrubygradle/JRubyExec : Unsupported major.minor version 52.0
```

What am i doing wrong or missing here? I'm not specifying anywhere a version of JRubyExec which it complains about.

Thank you again!

**Comment by mkristian** [comment]
@piersf we are still missing jdk9/jdk10 support - well it got stuck half way. we will have a look get this done. not sure about this JAVA_HOME problem and jdk8 - looks different.

**Comment by piersf** [comment]
@mkristian would it be possible to bring **rubygems.lasagna.io** back up? We're currently blocked and the solution you suggested in the provided link [the built-in Gem proxy](http://jruby-gradle.org/base/#using-the-built-in-gem-proxy) does not seem to solve the issue (before changing the JAVA_HOME). 

Thanks,

**Comment by mkristian** [comment]
@piersf please use http://rubygems-proxy.torquebox.org/releases instead. we are working on getting rid of any such proxy in the future.

**Comment by piersf** [comment]
@mkristian that worked. Thank you so much!
One last question - should we expect in the future that http://rubygems-proxy.torquebox.org/releases also goes down at some point? 


For anyone else running into this issue, this is how my `build.gradle` file ended up looking like:

```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:3.2.5'
        classpath 'com.github.jruby-gradle:jruby-gradle-plugin:1.4.0'
    }
}

repositories {
    mavenCentral()
    maven {
      name 'rubygems-release'
      url 'http://rubygems-proxy.torquebox.org/releases'
    }
}

apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin
apply plugin: com.github.jrubygradle.JRubyPlugin

dependencies {
    jrubyExec 'rubygems:rspec:3.3.0'
    jrubyExec 'rubygems:dockerspec:0.3.+'
}
```


Thanks,

**Comment by mkristian** [comment]
@piersf this one is maintained and used by torquebox. their build needs it but newer maven plugin/extensions do not need it. this server had some outages in the past so the lasagna server come into existing. so expect this server to be around for the time being as it was around for the many years now.

**Comment by mkristian** [comment]
this is not fixed but we do not support the lasagne server anymore - see also 3684c406b91e52d71375c2b881cc92f9b7bc0006

need to use torquebox proxy.

closing.
