### ISSUE TITLE
Issue using the ascii_binder gem with jruby-gradle-plugin.

### ISSUE THREAD

**Issue by wdschei** [jruby-gradle/jruby-gradle-plugin#333]
I have created a [Short, Self Contained, Correct (Compilable) Example](http://sscce.org/) or [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) project for working through the issues of using the `ascii_binder` gem with the `jruby-gradle-plugin` which can be found at https://github.com/wdschei/gradleAsciiBinder/.

Basically I'm getting the following when I try to use the `ascii_binder` gem with the `jruby-gradle-plugin`:
```
> Task :asciiBinder FAILED
Gem::MissingSpecError: Gem::MissingSpecError
                        to_specs at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/dependency.rb:308
  block in activate_dependencies at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:1439
                            each at org/jruby/RubyArray.java:1733
           activate_dependencies at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:1428
                        activate at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/specification.rb:1410
                    try_activate at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems.rb:220
                         require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:125
                          <main> at /.../gradleAsciiBinder/src/docs/asciidoc/asciiBinder.rb:2
```

I'm not even actually using it at this point. I'm just trying to load the version number.

The root cause seems to have something to do with the `yajl-ruby` dependency of `ascii_binder` which results in:
```
current directory: $HOME/Projects/gradleAsciiBinder/build/tmp/jrubyExec/gems/yajl-ruby-1.3.1/ext/yajl
/usr/lib/jvm/jdk1.8.0_152/jre/bin/java -cp :$HOME/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.1.7.0/d6b98ab4b7d9ad305e3331eca5528bd03960cf76/jruby-complete-9.1.7.0.jar org.jruby.Main -r ./siteconf20180827-20852-klp86k.rb extconf.rb
creating Makefile

current directory: $HOME/Projects/gradleAsciiBinder/build/tmp/jrubyExec/gems/yajl-ruby-1.3.1/ext/yajl
make "DESTDIR=" clean
Makefile:225: *** multiple target patterns.  Stop.

current directory: $HOME/Projects/gradleAsciiBinder/build/tmp/jrubyExec/gems/yajl-ruby-1.3.1/ext/yajl
make "DESTDIR="
Makefile:225: *** multiple target patterns.  Stop.

make failed, exit code 2
```

Am I missing something stupid here or is this a bug of some kind?

I'm not really a Ruby person, but I'm familiar with Gradle and several JVM languages, so any help is greatly appreciated.

**Comment by mkristian** [comment]
`yajl-ruby` is a gem with native extension which can not be used with jruby. sometimes there are pure ruby or jruby alternatives of some gems - not always.

**Comment by wdschei** [comment]
@mkristian Thanks for the clarification on this.
