### ISSUE TITLE
jar-dependencies pin from jruby-gradle-jar-plugin is very out of date

### ISSUE THREAD

**Issue by dgolombek** [jruby-gradle/jruby-gradle-plugin#338]
AFAICT, the pin of jar-dependencies in jruby-gradle-jar-plugin to 0.1.15 is escaping that plugin, and I've been unable to override it.

I have:

```
buildscript {
    repositories {
        maven { url "${artifactoryUrl}/jcenter" }
    }

    dependencies {
        //implementation 'rubygems:jar-dependencies:0.3.12'
        /* We need Grgit in our buildscript classpath for looking up our commit SHA-1 */
        classpath "org.ajoberstar:grgit:[1.3.0,1.4.0)"
        classpath('com.github.jruby-gradle:jruby-gradle-storm-plugin:[0.4.4,0.5)') {
            transitive = false
            exclude group: 'rubygems', module: 'jar-dependencies'
        }
        classpath('com.github.jruby-gradle:jruby-gradle-plugin:[1.1.4,1.2)') {
            transitive = false
            exclude group: 'rubygems', module: 'jar-dependencies'
        }
        classpath('com.github.jruby-gradle:jruby-gradle-jar-plugin:1.1.4') {
            exclude group: 'rubygems', module: 'jar-dependencies'
        }        
    }
}

configurations.all { 
    resolutionStrategy.force 'rubygems:jar-dependencies:0.3.12'
}

dependencies {
    gems 'rubygems:jar-dependencies:0.3.10+'
}
```

`./gradlew dependencies` shows:

> jrubyJar
> \--- rubygems:jar-dependencies:0.1.15
> jrubyStormLocal
> +--- rubygems:jar-dependencies:0.3.10+ FAILED

Obviously the easy solution is to remove the pin, BUT I think it'll also require updating jruby-gradle-storm-plugin, which doesn't seem to be compatible with jruby-gradle-plugin >= 1.2. I can submit a separate bug report on that if you'd like, but I don't have any real info beyond gradle saying 'Failed to apply plugin [id 'com.github.jruby-gradle.storm']. Could not create task of type 'JRubyStorm'.' Even with --debug, no explanation is provided.

**Comment by dgolombek** [comment]
Sorry, I badly misdiagnosed this at first. The problem is that setting the JRubyJar jruby version via 
a call such as assembleJRubyStorm { jrubyVersion '9.1.17.0' } (which invokes 
https://github.com/jruby-gradle/jruby-gradle-plugin/blob/release-1.1.x/jruby-gradle-jar-plugin/src/main/groovy/com/github/jrubygradle/jar/JRubyJar.groovy#L54-L58) calls addEmbeddedDependencies, which adds in the jar-dependencies 0.1.15 dependency (with no way to configure it).  If I instead do `project.assembleJRubyStorm.embeddedJRubyVersion = '9.1.17.0'` (which is clearly a hack), the dependency is not added and at least I can move forward (of course, at the risk of problems with jar-dependencies problems later on). 

So maybe the real request here to to allow specifying the version of jar-dependencies that jruby-gradle-jar-plugin injects as a dependency, or to update it to a newer version.

**Comment by rtyler** [comment]
From my understanding based on discussions years ago with @mkristian , I didn't believe that jar-dependencies was necessary in the JRuby 9.x release line because some fixes were actually upstreamed.

**Comment by dgolombek** [comment]
Hmmm, my understanding was that jar-dependencies was generally being displaced by warbler, rather than not being needed anymore. JRuby 9k in fact still embeds jar-dependencies into jruby-complete, although I can't say that's by intent rather than being left behind. This version mismatch was one of several I was running into.

In any case, I know this project isn't a top priority, and we're slowly moving away from Storm, and I have a work-around, so not a big deal.

**Comment by mkristian** [comment]
my 2 cents: jar-dependencies is a default in JRuby and will be for the time being. so you will have it with jruby-complete and jruby-stdlib. not sure if jruby-gradle plugin needs to add this explicitly with jruby-9k, for old jruby-1.7.x this is needed. not sure, need to look into jruby-gradle code to see. but any 'installed' jar-dependencies will be activated by rubygems if installed overriding the default gem.

**Comment by rtyler** [comment]
I have added this to the 2.0 milestone.

I think the right behavior with 2.0 would be to rip out the remainder of the JRuby 1.7.x support and make JRuby/Gradle explicitly JRuby 9.x and later only.

**Comment by mkristian** [comment]
👍 for going jruby9 only

**Comment by rtyler** [comment]
Removed for 2.x
