### ISSUE TITLE
Cannot install latest "selenium-webdriver" gem

### ISSUE THREAD

**Issue by boris-petrov** [jruby-gradle/jruby-gradle-plugin#341]
Original issue was in the [jruby repo](https://github.com/jruby/jruby/issues/5708).

This is a simple [reproduction](https://github.com/jruby/jruby/issues/5708#issuecomment-486831646).

**Comment by rtyler** [comment]
Thanks @boris-petrov.

I've been doing some testing locally with this, and it seems like the mkrf_conf.rb from the childprocess gem runs _fine_ just by itself. But then there's another subprocess being run:

```
current directory: /home/tyler/source/github/jruby-gradle/jruby-5708/build/tmp/jrubyExec/gems/childprocess-1.0.1/ext
/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/bin/java -cp :/home/tyler/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.2.7.0/308120bca38f617e7b275af8ce0cbd9f0be66218/jruby-complete-9.2.7.0.jar org.jruby.Main mkrf_conf.rb

current directory: /home/tyler/source/github/jruby-gradle/jruby-5708/build/tmp/jrubyExec/gems/childprocess-1.0.1/ext
jrake RUBYARCHDIR=/home/tyler/source/github/jruby-gradle/jruby-5708/build/tmp/jrubyExec/extensions/universal-java-1.8/2.5.0/childprocess-1.0.1 RUBYLIBDIR=/home/tyler/source/github/jruby-gradle/jruby-5708/build/tmp/jrubyExec/extensions/universal-java-1.8/2.5.0/childprocess-1.0.1
sh: jrake: command not found

rake failed, exit code 127
```

It's not clear at all where the second command is coming from, still digging.
The second command

**Comment by rtyler** [comment]
This is definitely something weird with the `childprocess` gem. My current hunch is that the fact that it's native extension writes out a `Rakefile` is causing some machinery to try to run Rake invocation _somewhere_ before completing the gem installation process.

```gradle
plugins {
	id 'com.github.jruby-gradle.base' version '1.6.0'
}

jruby {
    defaultVersion '9.2.7.0'
    execVersion '9.2.7.0'
}

dependencies {
	jrubyExec 'rubygems:childprocess:1.0.1'
}

import com.github.jrubygradle.JRubyExec

task foobar(type: JRubyExec) {
	script 'gem'
}

```

```
➜  jruby-5708  gw foobar
:foobar
Building native extensions. This could take a while...
ERROR:  Error installing /home/tyler/.gradle/caches/modules-2/files-2.1/rubygems/childprocess/1.0.1/2196a2de665622e2135ddfb46c653e4f3e3ede51/childprocess-1.0.1.gem:
	ERROR: Failed to build gem native extension.

    current directory: /home/tyler/source/github/jruby-gradle/jruby-5708/build/tmp/jrubyExec/gems/childprocess-1.0.1/ext
/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/bin/java -cp :/home/tyler/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.2.7.0/308120bca38f617e7b275af8ce0cbd9f0be66218/jruby-complete-9.2.7.0.jar org.jruby.Main mkrf_conf.rb

current directory: /home/tyler/source/github/jruby-gradle/jruby-5708/build/tmp/jrubyExec/gems/childprocess-1.0.1/ext
jrake RUBYARCHDIR=/home/tyler/source/github/jruby-gradle/jruby-5708/build/tmp/jrubyExec/extensions/universal-java-1.8/2.5.0/childprocess-1.0.1 RUBYLIBDIR=/home/tyler/source/github/jruby-gradle/jruby-5708/build/tmp/jrubyExec/extensions/universal-java-1.8/2.5.0/childprocess-1.0.1
sh: jrake: command not found

rake failed, exit code 127

Gem files will remain installed in /home/tyler/source/github/jruby-gradle/jruby-5708/build/tmp/jrubyExec/gems/childprocess-1.0.1 for inspection.
Results logged to /home/tyler/source/github/jruby-gradle/jruby-5708/build/tmp/jrubyExec/extensions/universal-java-1.8/2.5.0/childprocess-1.0.1/gem_make.out
Successfully installed rake-12.3.2
1 gem installed
:foobar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':foobar'.
> Process 'command '/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
1 actionable task: 1 executed

```

**Comment by rtyler** [comment]
I cannot for the life of me figure out where this `jrake` invocation is _actually_ coming from.

**Comment by rtyler** [comment]
@boris-petrov I will note that the gems are installed properly, nothing is failing. So if you ignore that failure on the gem installation, everything else should work just fine in the JRuby/Gradle environment

**Comment by rtyler** [comment]
I have found [where this code is coming from](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/ext/rake_builder.rb).

In a `jruby-complete` environment, the `Gem.bin_path('rake', 'rake')` line throws an exception, and then the rescue block runs, using `Gem.default_exec_format` which is `j%s` in this environment.

So basically it looks like the problem is that `childprocess` has a `runtime_dependency` on `rake`, which **must** be resolved and present for the _install_ of `childprocess` to work properly.

This explains why repeatedly running the command works

**Comment by rtyler** [comment]
We do set `GEM_HOME` and `GEM_PATH` in the right place in `GemUtils.groovy` to pick up the `rake` executable, but because we're optimizing for a single invocation:

```
/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/bin/java -Dfile.encoding=utf-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /home/tyler/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.2.7.0/308120bca38f617e7b275af8ce0cbd9f0be66218/jruby-complete-9.2.7.0.jar org.jruby.Main -S gem install /home/tyler/.gradle/caches/modules-2/files-2.1/rubygems/childprocess/1.0.1/2196a2de665622e2135ddfb46c653e4f3e3ede51/childprocess-1.0.1.gem /home/tyler/.gradle/caches/modules-2/files-2.1/rubygems/rake/12.3.2/e4da045eeb31ada2c4bc7f05f8339866d245bd20/rake-12.3.2.gem --ignore-dependencies --install-dir=/home/tyler/source/github/jruby-gradle/jruby-5708/build/tmp/jrubyExec --no-user-install --wrappers --no-document --local
```

The `childprocess` gem gets installed before `rake`.

I think the dumb/simple solution would be to invoke `gem install` for each gem independently. The smart/hard solution would be to intelligently order the list of `.gem` files passed to this command.

**Comment by rtyler** [comment]
:oncoming_police_car:  CLEVER IDEA :oncoming_police_car: 

Gradle will represent this dependency tree:

```
jrubyExec
+--- rubygems:sinatra:[0,) -> 2.0.5
|    +--- rubygems:rack:[2.0,2.99999] -> 2.0.7
|    +--- rubygems:tilt:[2.0,2.99999] -> 2.0.9
|    +--- rubygems:rack-protection:[2.0.5,2.0.5.0.0.0.0.1) -> 2.0.5
|    |    \--- rubygems:rack:[0,) -> 2.0.7
|    \--- rubygems:mustermann:[1.0,1.99999] -> 1.0.3
+--- rubygems:childprocess:1.0.1
|    \--- rubygems:rake:[0,13.0) -> 12.3.2
\--- org.jruby:jruby-complete:9.2.7.0
```

when converted to a `FileCollection` as this array:

```
sinatra-2.0.5.gem,childprocess-1.0.1.gem,rack-protection-2.0.5.gem,rack-2.0.7.gem,tilt-2.0.9.gem,mustermann-1.0.3.gem,rake-12.3.2.gem
```

So it _appears_ that if we simply reverse the order, we'll install the deepest dependencies in the tree first. :tada:

**Comment by boris-petrov** [comment]
@rtyler - looks great, thank you for the great support! I'm looking forward to trying it out in a newly released version of `JRuby/Gradle`. :)

**Comment by mkristian** [comment]
@rtyler cool finding. the 'trick' is actually the right thing to do to start with the deepest dependencies of the tree.

**Comment by boris-petrov** [comment]
@rtyler - thank you very much for going deep into this and figuring it out! Can we expect a new version soon with that fix?

**Comment by rtyler** [comment]
@boris-petrov Once I can figure out how what the test failures in #343 are, then I will create another release. I'm hopeful that we can get it out before next Monday

**Comment by rtyler** [comment]
@boris-petrov 1.7.0 has now been released

**Comment by boris-petrov** [comment]
@rtyler - thanks for the great support!
