### ISSUE TITLE
Switch to a Rubygems proxy which runs over TLS

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#349]
Right now we hit `http://rubygems-proxy.torquebox.org/releases`, which when accessed over HTTPs has an invalid certificate.

**Comment by rtyler** [comment]
Looks like this is already an active request: https://github.com/torquebox/rubygems-servlets/issues/17

But I'm pinging @bbrowning nonetheless

**Comment by rtyler** [comment]
Related to this, I have also pinged the rubygems.org maintainers about upstreaming the maven functionality. Whether that's through rubygems-servlets, or by teaching the rubygems app how to emit XML

**Comment by bbrowning** [comment]
The rubygems-proxy.torquebox.org server is unmaintained and has been that way for a few years. I'd strongly suggest anything referencing it point to something else.

**Comment by ysb33r** [comment]
#364 takes care of this.

**Comment by rtyler** [comment]
Closing this in favor of the work @ysb33r has been doing
