### ISSUE TITLE
Investigate using a local lightweight proxy rather than Torquebox

### ISSUE THREAD

**Issue by ysb33r** [jruby-gradle/jruby-gradle-plugin#364]
Investigate the possibility of using a lightweight local proxy inside Gradle  rather than Tortquebox or going through the maven-wagon protocol. The idea is that if succesfull, this should displace the following defects:

- #349

Consider doing the following:

- [x] Run a lightweight proxy server inside Gradle using Ratpack or Micronaut.
- [x] Cache lookups in Gradle cache.
- [x] Resolve metadata for a dependency with transitive dependencies and cache locally.
- [x] Implement direct access to the Rubygems REST API (v1 & v2).
- [x] Implement Gem to Ivy.xml transformation.
- [x] Implement `/{group}/{module}/{revision}/ivy.xml`.
- [x] Implement `/{group}/{module}`.
- [x] Embed only such server per full project (not per subproject)
- [x] Use an Ivy proxy rather than Maven as it is easier to split lookups between servers. In this way we can lookup up an ivy.xml via the local proxy but retrieve the GEM directly from `rubygems.org` (or another server).
- [x] Ensure that caching is safe between Gradle instances
- [x] Ensure that caching is safe between threads within the same Gradle instance
- [x] Allow `--refresh-dependencies` to redo the lookups
- [x] Expire ivy.xml caches after a set period of time.
- [x] Implement debug logging mode.
- [x] Add a `RepositoryHandler` extension.

**Comment by rtyler** [comment]
@ysb33r everything is checked here does that mean your experiments have been successful :joy_cat:
