### ISSUE TITLE
Release 2.0.0 alpha 

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#379]
We need a first alpha release so people can start testing the new resolution functionality.

Unfortunately the way that plugins.gradle.org syncs from bintray means this is likely going to be suggested to anybody that lands on the plugins.gradle.org page for jruby-gradle

**Comment by ysb33r** [comment]
We can change it to publish straight to plugins.gradle.org and then if you want still write a backup to bintray.

**Comment by rtyler** [comment]
Bintray is not the problem, plugins.gradle.org is. They show whatever the latest version in their info pages

**Comment by ysb33r** [comment]
Right I see what you are saying. For that I have a solution that we use in Asciidoctor-Gradle.

We could have something like this defined

```groovy
    pluginExtraText = (version.contains('-alpha') || version.contains('-beta')) ?
        " (If you need a production-ready version of the JRuby plugins for Gradle use a 1.7 release of this plugin instead)"
        : ''
```

adn then where we provide the plugin text just add that variable.

**Comment by rtyler** [comment]
Published alpha1
