### ISSUE TITLE
rubygems.lasagna.io domain has lapsed

### ISSUE THREAD

**Issue by jdomingu** [jruby-gradle/jruby-gradle-plugin#384]
First, this is an awesome project, so thanks for all your work!

I'm seeing errors for all requests to rubygems.lasagna.io. Navigating to the domain in a browser shows a message that the domain is for sale:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/5760201/63065982-02685880-bebd-11e9-81c8-2856dd8353f8.png">

Is this server still going to be supported in the future? If not, it would be great if the docs were updated. For now, I'm using the built-in proxy server described here as a workaround:
<http://jruby-gradle.org/base/#using-the-built-in-gem-proxy>

Let me know if there's a better option 😃

**Comment by rtyler** [comment]
Heh, that's a pretty funny domain squat. The service was discontinued last year or the year before, I formerly ran it :smile_cat: 


More recent versions of the plugin default to rubygems.torquebox.org which is a slightly more maintainer proxy. Our alphas of 2.0.0 don't require a proxy, so if you're interested in helping us get that out the door, you could test it out

**Comment by jdomingu** [comment]
Thanks for the fast reply! I will try upgrading or pointing to another proxy server.
