### ISSUE TITLE
Remove all dependencies on Torquebox

### ISSUE THREAD

**Issue by ysb33r** [jruby-gradle/jruby-gradle-plugin#388]

**Comment by ysb33r** [comment]
In 2.0.0-alpha2

**Comment by patburns** [comment]
Because torque box is current down my team is very interested in this.  Have any idea of when you might release 2.0.0?

**Comment by ysb33r** [comment]
@patburns Pull the latestalpha version. the final version is expected to be out early Jan 2020.
