### ISSUE TITLE
Cannot change the JRuby version that is used by the `jrubyPrepare` tasks

### ISSUE THREAD

**Issue by boris-petrov** [jruby-gradle/jruby-gradle-plugin#390]
Check [this project](https://github.com/boris-petrov/jruby-gradle-bug).

If you change the `jruby.jrubyVersion = '9.2.9.0'` line to, say, `jruby.jrubyVersion = '9.2.7.0'` and run `gradle rubocop`, you'll see that still the default `9.2.9.0` version is used. In the documentation it is specified that this is a global property and should change the JRuby version for all tasks but it doesn't. This does, instead:

```gradle
tasks['jrubyPrepareRubocop'].jruby.jrubyVersion = jRubyVersion
```

**Comment by ysb33r** [comment]
:man_facepalming: I think I found the cause of this.

**Comment by ysb33r** [comment]
In 2.0.0-alpha.3
