### ISSUE TITLE
[2.0.0-alpha.3] Cannot install http-cookie gem

### ISSUE THREAD

**Issue by boris-petrov** [jruby-gradle/jruby-gradle-plugin#393]
Thanks for fixing the other issue with the RuboCop gem!

[Here is a reproduction repo](https://github.com/boris-petrov/jruby-gradle-bug). Run `gradle jrubyPrepare` on that. It fails with:

```
Building native extensions. This could take a while...
ERROR:  Error installing /home/boris/.gradle/caches/modules-2/files-2.1/rubygems/unf/0.2.0.beta2/6c4c61b91e077c299138b584c8eace2bacd9ceab/unf-0.2.0.beta2.gem:
	ERROR: Failed to build gem native extension.

    current directory: /home/boris/jruby-gradle-bug/build/.gems/gems/unf-0.2.0.beta2/ext
/usr/lib/jvm/java-13-openjdk/bin/java -cp :/home/boris/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.2.9.0/8e44ce7a1417966d89957bd766a148601e28828b/jruby-complete-9.2.9.0.jar org.jruby.Main mkrf_conf.rb
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/home/boris/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.2.9.0/8e44ce7a1417966d89957bd766a148601e28828b/jruby-complete-9.2.9.0.jar) to method sun.nio.ch.NativeThread.signal(long)
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

current directory: /home/boris/jruby-gradle-bug/build/.gems/gems/unf-0.2.0.beta2/ext
jrake RUBYARCHDIR=/home/boris/jruby-gradle-bug/build/.gems/extensions/universal-java-13/2.5.0/unf-0.2.0.beta2 RUBYLIBDIR=/home/boris/jruby-gradle-bug/build/.gems/extensions/universal-java-13/2.5.0/unf-0.2.0.beta2
sh: jrake: command not found

rake failed, exit code 127

Gem files will remain installed in /home/boris/jruby-gradle-bug/build/.gems/gems/unf-0.2.0.beta2 for inspection.
Results logged to /home/boris/jruby-gradle-bug/build/.gems/extensions/universal-java-13/2.5.0/unf-0.2.0.beta2/gem_make.out
```

**Comment by boris-petrov** [comment]
https://github.com/jruby-gradle/jruby-gradle-plugin/issues/341 seems like a similar issue - that is, `jrake` was also the problem there. @rtyler managed to fix it. Perhaps something similar is going on here with `2.0.0-alpha.3`?

**Comment by ysb33r** [comment]
@boris-petrov The issue tehre was that rake instead of jrake was selected ?

**Comment by boris-petrov** [comment]
@ysb33r - no, I didn't follow completely what the issue was, but [this commit](https://github.com/jruby-gradle/jruby-gradle-plugin/commit/8194b27b9f9db84abc34535a91f409ddf414fa20) was the one that fixed it. Perhaps that gives you some idea?

**Comment by NiaTheBat** [comment]
4

**Comment by ysb33r** [comment]
That integration tests still exists and passes, something else is now at play.

**Comment by boris-petrov** [comment]
@ysb33r - the integration test is for a different gem. Perhaps you could add a test with the `build.gradle` I've given in the reproduction repo - that should fail.

**Comment by ysb33r** [comment]
@boris-petrov Firstly, doing the following will work around your problem
```
        gems 'rubygems:unf:0.1.4', {
                force = true
        }
```

It seems that the 2.0.0.beta2 GEM of `unf` does not detect the JRuby environment correctly and tries to install the native extension. You might want to raise an issue with the authors of that GEM.
(Maybe there is something that we can fix in the plugin itself, but I am not sure about that).

**Comment by ysb33r** [comment]
I've just tested it and the GEM can actually be used to build a java variant, so the author should just publish the java variant as well to rubygems.

**Comment by boris-petrov** [comment]
@ysb33r - thanks, that workaround works! The question remains - why does this work "out-of-the-box" for JRuby/Gradle 1.7.0 but fails on 2.0.0-alpha.4? The same gem is used. Perhaps a different version is resolved?

**Comment by ysb33r** [comment]
@boris-petrov I figured it out. The old version does not resolve any "development" versions. It was supposed to be a feature of 2.x to turn that option on or off.

**Comment by boris-petrov** [comment]
@ysb33r - great, thanks for the support! So... how do I turn that option off? I think it should be "off" by default.

**Comment by ysb33r** [comment]
It will be in 2.0.0-alpha.7

If you do 
```
repositories {
   ruby.gems()
}
```
prerelease GEMs will no longer be considered as you would expect.

But you can do
```
repositories {
    ruby.gems {
       prerelease = true
   }
}
```
if you do need them.
