### ISSUE TITLE
Move repository under jruby organization

### ISSUE THREAD

**Issue by headius** [jruby-gradle/jruby-gradle-plugin#408]
It appears a lot of issues have gone unnoticed by the JRuby team, and I am thinking maybe we should consider moving this repository under the `jruby` organization and supporting it from there. That would make it easier to track updates, at least, and perhaps the centralized management would mean we can support this project better.

Thoughts, @rtyler @enebo?

**Comment by ysb33r** [comment]
I would be more than happy for this to happen.

**Comment by rtyler** [comment]
I'm fine with that. We can probably leave everything else here for now.

**Comment by rtyler** [comment]
@headius made you an owner in this organization, you can initiate the transfer

**Comment by headius** [comment]
@rtyler I was about to say making us part owners would also be a possibility. I'll confer with @enebo and try to decide what's the best option. I wish there was a concept of sub-organizations!

**Comment by boris-petrov** [comment]
Is there any progress on this issue, @headius? Actually it doesn't really matter where the repo is - the important part is that the project is not really supported any more unfortunately. There are issues that prevent gem installations, upgrading to Gradle 8, etc. Any suggestions for further steps?

**Comment by UweKubosch** [comment]
Any progress?  A new release with the current code would be nice.

I can help if needed.

**Comment by enebo** [comment]
@UweKubosch I will ping @headius this morning.  This topic got lost to the sands of time again (which is a tad ironic given the issue).

**Comment by enebo** [comment]
@UweKubosch we would love it if you could take a stab at updating/releasing for Gradle 8/modern times.   As @boris-petrov said, we need to update this more than anything else (e.g. support it).  For anyone else paying attention this is a great opportunity to help out.  We support so many things it is difficult to keep track.  @UweKubosch if you need access to this repo we can add you.

Assuming we get something out and address some of the issues on this repository we can move this over to the main JRuby org.  Since we have open relevant issues here I think it makes sense to get back on track with this repo before considering moving this and any other repos in this org over.

**Comment by UweKubosch** [comment]
We use this plugin in our projects, so maintaining the current feature set should be OK for us.

As far as I know, the current master works for Gradle 8 and should be released.

Step 1 should be to fix the release process.  As I see it, version 2.1.0-alpha.3 should have been released last May, but the process failed.

Given access, I can work on getting things working and released, and the triage current pull requests and issues.

**Comment by ysb33r** [comment]
We have one of two options.

(1) Simply give the appropriate people form jruby access to the jruby-gradle group

(2) Give someone from the jruby group access to the jruby-gradle group, who can then move all the project to jruby group.

Which one would people prefer? I'll do the necessary once I know.

**Comment by enebo** [comment]
@ysb33r At this point just giving @UweKubosch access would be a first good step.  Giving us (@enebo, @headius) access I think also gives us the ability to move it over once we make it past this point of getting something out.

**Comment by enebo** [comment]
@ysb33r thanks!  Once something is out we will figure out what we should do with moving or not.  @UweKubosch Also thanks again for picking up another JRuby-related project.

**Comment by UweKubosch** [comment]
Thank you for the access.  Glad to be able to contribute!  😄
