### ISSUE TITLE
Requesting non-alpha 2.1.0 release

### ISSUE THREAD

**Issue by madrob** [jruby-gradle/jruby-gradle-plugin#431]
I'm trying to migrate a project off of jcenter which stopped working very recently (maybe a cache expired or whatever) and have run into issues with this plugin. I saw #420 and it looks like that has been successful, because I see versions available at https://plugins.gradle.org/plugin/com.github.jruby-gradle.base

Version 2.0.1 (and 2.0.2 which exists at https://plugins.gradle.org/plugin/com.github.jruby-gradle.base/2.0.2 but not tagged in this repo) both depend on version 0.x of @ysb33r/grolifant that never made it to maven central.

The versions that have updated grolifant which can be found on maven central are all 2.1.0-alpha releases. Same sort of thing happened there by the way - alpha.2 exists in the plugin portal but not in the repo. Anyway, we can switch to an alpha release, but it would be nice to have a stable release where we can migrate since the old ones are slowly becoming inaccessible.

Originally I started the journey on https://issues.apache.org/jira/browse/SOLR-15915 and there's some optional detail, but less organized, over there.

**Comment by UweKubosch** [comment]
Will try to push a release this week.

**Comment by boris-petrov** [comment]
@UweKubosch, @donv - I'm not sure where these releases are going. In the [Plugin Portal](https://plugins.gradle.org/search?term=com.github.jruby-gradle) all seems as it was before. How can I try out the new beta versions?

**Comment by donv** [comment]
The releases are going to Plugin Portal, but they are pending manual approval, and I don't have access to the account to see exactly what is wrong.

@rtyler can you see what the problem is or share the account with me?

**Comment by boris-petrov** [comment]
Any news on this? :) I really want to try the new version to see if it works on Gradle 8 (although it probably still will have problems, for example due to https://github.com/jruby-gradle/jruby-gradle-plugin/issues/435).

**Comment by UweKubosch** [comment]
Hi!  I am trying to get this moving, but I will not have any time for this for the next two weeks.

**Comment by boris-petrov** [comment]
@UweKubosch, @donv, @rtyler sorry to push so much but any progress on releasing to the plugin portal? :)
