### ISSUE TITLE
Define JRuby dependency using custom dependency scope named jrubySdk

### ISSUE THREAD

**Issue by mojavelinux** [jruby-gradle/jruby-gradle-plugin#96]
To follow common conventions in the Gradle ecosystem, I think the version of the JRuby dependency should be defined using a custom dependency scoped named `jrubySdk` instead of in the `jruby` configuration stanza.

You can see this convention in practice in the Google App engine plugin:

```
dependencies {
  appengineSdk 'com.google.appengine:appengine-java-sdk:1.9.17'
}
```

See https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/blob/master/README.md

This allows the user of the plugin to define JRuby their own way. We could provide it out of the box, but overridding this dependency declaration would allow them provide JRuby their own way (perhaps using individual artifacts instead of jruby-complete or a local file).

Having said that, the Android plugin defines the SDK version using the `android` stanza, but it doesn't seem to obtain the dependency from a repository, so perhaps it's a different scenario.

**Comment by rtyler** [comment]
We're fast approaching 1.0, and I'm not sure I agree with the original reasoning in this ticket any longer. I'm going to close it out since I do not see a compelling argument anymore for modifying the `jruby{}` closure.
